language: python
python:
  - "3.3"

install: "pip install -r requirements.txt"
script:
- nose2

after_success:
- scripts/ci/deploy.sh

env:
  global:
    - OSGEO_USERNAME=mkuhn
    # Inject OSGEO_PASSWORD matching the OSGEO_USERNAME
    # Generate with the following command for proper special characters support
    #     travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    - secure: "eEt7uqkJBoJWgrDk4rwFHuL0zudEzdj+3kiANRhJXmmmeR46zVkyt3naJGIE2OjAUV3g9s06JciGNzyUxgjhl0UBj2CNqgQd1NTUWdJEiumD00geXyTnLfyz6vl0DG/S1zW9SAtCNkwHGwg6z/MedS1kODj0RApZUmq1MVE+FaremryLp61MCPVuuVslX65Te1XbfKGiQLjSa4TjRzUClL2xSHzFWmAHYIrPoib1UoS5F/BJEXCqR8bTtR9pt72V56PeV5nvReXe5fhukOylxtf3/c+bNpEM2f51tr5f2IrOMHYPD6JfpvBp1SWqdVAmx0P8iLaFa3tXTtC7HFyKhib9k6auE4u4/c4XN46beic6cKNtYkbJ4ttQg8TDA+h4y66VumoRWgJrYxv3OJLTj8SQEQCXEkdYSzpvwdnw/hi3hCkwa2Yyl9VGrcIzx3/xBQwnCZBw1sqNdEHakeKu/XogPt/0VBRzaFvDjhHofyHcOcz3z/IPPtEj9WV7nruWCkeR+kkhPZPrS1+2GnG0BfHhJh8yUSxOfcf6NUR/3BNlO3csVXU594Ct8vQ7VBiEx2Vj4BAhANBLLR1vNXr70c5v+2R5KKY/DeZwtd9cEEbY9koxIpwRwZj8ye5DpZo1+rTxNY17V0WaWIt9ZXheBx2iSlGiMSdBIYQqyyrWXZ0="
